### ISSUE TITLE
[BUG?] Not inserted records into files table.

### ISSUE THREAD

**Issue by mzch** [WeebDev/chibisafe#247] opened 2021-01-06 20:57 UTC
**Describe the bug**
When finished upload a file, chibisafe doesn't insert a record into `files` table. So selecting `Upload` tab, no file is shown.

**To Reproduce**
1. Go to 'Home'
2. Drag and Drop a file in `Drag & Drop your files or click to browse` zone.
3. Upload finished.
4. Select `Uploads` tab.
5. No file is shown. (No record is inserted into `files` table`)

**Expected behavior**
Show uploaded file

**Screenshots**
After upload:
<img width="1494" alt="ScreenShot01" src="https://user-images.githubusercontent.com/621178/103818788-7f94fe80-50ac-11eb-8b12-33a13b380af6.png">

Show `Uploads` tab:
<img width="1494" alt="ScreenShot02" src="https://user-images.githubusercontent.com/621178/103818815-90457480-50ac-11eb-9c3d-fb7969561792.png">

**Additional context**
- DATABASE: PostgreSQL 13
- Node.js: v12.20.0
- npm: 6.14.10
- chibisafe: commit f9444691627d6168511a5066553dae6dc0390c58

- DB Records:
```
chibisafe=# select * from "albumsFiles";
 id | albumId | fileId
----+---------+--------
(0 rows)

chibisafe=# select * from files;
 id | userId | name | original | type | size | hash | ip | createdAt | editedAt
----+--------+------+----------+------+------+------+----+-----------+----------
(0 rows)
```
- `uploads` directory:
```
chibisafe@x03:~/chibisafe/uploads$ ls -l
total 928
-rw-r--r-- 1 chibisafe chibisafe 472036 Jan  6 12:46 7y9kaed7tv1m.jpg
drwxr-xr-x 2 chibisafe chibisafe      6 Jan  6 12:42 chunks
drwxr-xr-x 4 chibisafe chibisafe     35 Jan  6 12:42 thumbs
-rw-r--r-- 1 chibisafe chibisafe 472036 Jan  6 12:50 z5xhasbjlhnv.jpg
```

**Comment by BobbyWibowo** [comment] 2021-01-06 21:07
:thinking: did you run `npm i` after pulling the commit? as it introduced a new dependency, which is indeed specific for uploads

**Comment by BobbyWibowo** [comment] 2021-01-06 21:11
also do `npm run build` afterwards to rebuild frontend. the said commit also added a small change to homepage uploader, that'd break your chunked uploads specifically until you rebuilt

**Comment by mzch** [comment] 2021-01-06 21:11
Yes. After cloning the repository freshly, I ran `npm i` then `npm run setup`.

**Comment by mzch** [comment] 2021-01-06 21:30
One another error:
```
chibisafe@x03:~/chibisafe$ npm install

> deasync@0.1.21 install /srv/chibisafe/chibisafe/node_modules/deasync
> node ./build.js

`linux-x64-node-12` exists; testing
Binary is fine; exiting

> bcrypt@5.0.0 install /srv/chibisafe/chibisafe/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
[bcrypt] Success: "/srv/chibisafe/chibisafe/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" is installed via remote

> blake3@2.1.4 install /srv/chibisafe/chibisafe/node_modules/blake3
> node -e "try{require('./dist/build/install')}catch(e){}"

API version for node@v12.20.0 linux not explicitly built, falling back to latest. If this does not work, open an issue at https://github.com/connor4312/blake3/issues/new
Retrieving native BLAKE3 bindings for Node v12 on linux...
Error trying to import bindings: Error: /srv/chibisafe/chibisafe/node_modules/blake3/dist/native.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeEPKNS_9CFunctionE
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /srv/chibisafe/chibisafe/node_modules/blake3/dist/build/install.js:51:13
    at Generator.next (<anonymous>)
    at fulfilled (/srv/chibisafe/chibisafe/node_modules/blake3/dist/build/install.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
BLAKE3 will use slower WebAssembly bindings when required in Node.js

> node-sass@5.0.0 install /srv/chibisafe/chibisafe/node_modules/node-sass
> node scripts/install.js

Cached binary found at /srv/chibisafe/.npm/node-sass/5.0.0/linux-x64-72_binding.node

> puppeteer@5.5.0 install /srv/chibisafe/chibisafe/node_modules/puppeteer
> node install.js

Downloading Chromium r818858 - 132.1 Mb [====================] 100% 0.0s
Chromium (818858) downloaded to /srv/chibisafe/chibisafe/node_modules/puppeteer/.local-chromium/linux-818858

> sharp@0.27.0 install /srv/chibisafe/chibisafe/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /srv/chibisafe/.npm/_libvips/libvips-8.10.5-linux-x64.tar.br

> sqlite3@5.0.0 install /srv/chibisafe/chibisafe/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
[sqlite3] Success: "/srv/chibisafe/chibisafe/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node" is installed via remote

> core-js@2.6.11 postinstall /srv/chibisafe/chibisafe/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> ejs@2.7.4 postinstall /srv/chibisafe/chibisafe/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> core-js@3.7.0 postinstall /srv/chibisafe/chibisafe/node_modules/plyr/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> node-sass@5.0.0 postinstall /srv/chibisafe/chibisafe/node_modules/node-sass
> node scripts/build.js

Binary found at /srv/chibisafe/chibisafe/node_modules/node-sass/vendor/linux-x64-72/binding.node
Testing binary
Binary is fine

> nodemon@1.19.4 postinstall /srv/chibisafe/chibisafe/node_modules/nodemon
> node bin/postinstall || exit 0


> nuxt@2.12.2 postinstall /srv/chibisafe/chibisafe/node_modules/nuxt
> opencollective || exit 0


                                                            :-:
                                                          .==-+:
                                                         .==. :+- .-=-
                                                        .==.   :==++-+=.
                                                       :==.     -**: :+=.
                                                      :+-      :*+++. .++.
                                                     :+-      -*= .++: .=+.
                                                    -+:      =*-   .+*: .=+:
                                                   -+:     .=*-     .=*-  =+:
                                                 .==:     .+*:        -*-  -+-
                                                .=+:.....:+*-.........:=*=..=*-
                                                .-=------=++============++====:

                                                Thanks for installing nuxtjs 🙏
                                        Please consider donating to our open collective
                                               to help us maintain this package.

                                                   Number of contributors: 0
                                                     Number of backers: 402
                                                     Annual budget: $86,141
                                                    Current balance: $58,621

                                  👉  Donate: https://opencollective.com/nuxtjs/donate

npm WARN chibisafe@4.0.1 scripts['tests'] should probably be scripts['test'].
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 2155 packages from 1073 contributors in 111.613s
```
Is it related with this issue?

**Comment by BobbyWibowo** [comment] 2021-01-06 21:41
The blake3 error is unfortunately an upstream-dependency issue.
It had been reported, and supposedly fixed, but the dev of blake3 npm package hasn't pushed a new release containing the fix yet.

Nonetheless, the said error shouldn't be related with the issue, since it'd fallback just fine to WebAssembly-mode, as the error message claimed.

Anyway, things work fine on my machine with the said commit, but unfortunately I only tested it with sqlite, the one point where our configurations differ.
I cannot test with pgsql for the time being though, so i can't say much. Perhaps try with sqlite to see if it's indeed specific to pgsql.

**Comment by Zephyrrus** [comment] 2021-01-06 22:07
I was able to reproduce this issue with PostgreSQL (v12) when uploading a file. The error is caused by these lines https://github.com/WeebDev/chibisafe/blob/f9444691627d6168511a5066553dae6dc0390c58/src/api/utils/Util.js#L229 https://github.com/WeebDev/chibisafe/blob/f9444691627d6168511a5066553dae6dc0390c58/src/api/utils/Util.js#L231 because the column in the database is called `userId` and not `userid`.

Seems like most SQL DB installations are case-insensitive by default while pg is case-sensitive by default, and that's how this issue was able to sneak past our testing.

**Comment by mzch** [comment] 2021-01-06 22:38
Well, I'm glad the cause is found. I'm looking forward to fixing this. :)

**Comment by mzch** [comment] 2021-01-06 22:54
I tried mariadb with `lower_case_table_names  = 1`, then the similar problem occurred.

**Comment by Pitu** [comment] 2021-01-07 04:24
@mzch could you check if it's fixed with this commit 9da45d616072cfaa535b539c2ecfdf96133fe381?

**Comment by mzch** [comment] 2021-01-07 22:24
Great! I can upload files successfully using both PostgreSQL and MariaDB. :)

But when creating an album, I need reload a page to see a new album on my browser using PostgreSQL.

**Comment by Pitu** [comment] 2021-01-08 16:32
@mzch this should be fixed in the latest release. Do a pull and restart, if the problem persists please re-open this issue

**Closed by Pitu** 2021-01-08 16:32 UTC
Labels: bug
